"""empty message

Revision ID: 129b468c74c0
Revises: e4a2e8d219dc
Create Date: 2020-06-03 18:07:25.249563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129b468c74c0'
down_revision = 'e4a2e8d219dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artists', sa.Integer(), nullable=False))
    op.add_column('Show', sa.Column('venues', sa.Integer(), nullable=False))
    op.drop_constraint('Show_artist_fkey', 'Show', type_='foreignkey')
    op.drop_constraint('Show_venue_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Venue', ['venues'], ['id'])
    op.create_foreign_key(None, 'Show', 'Artist', ['artists'], ['id'])
    op.drop_column('Show', 'artist')
    op.drop_column('Show', 'venue')
    op.add_column('Venue', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    op.add_column('Show', sa.Column('venue', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Show', sa.Column('artist', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_venue_fkey', 'Show', 'Venue', ['venue'], ['id'])
    op.create_foreign_key('Show_artist_fkey', 'Show', 'Artist', ['artist'], ['id'])
    op.drop_column('Show', 'venues')
    op.drop_column('Show', 'artists')
    # ### end Alembic commands ###
