"""empty message

Revision ID: 47f466c67790
Revises: 
Create Date: 2020-06-15 12:01:37.792686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f466c67790'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'price', 'stock', ['code'], ['code'])
    op.add_column('trader_stocks', sa.Column('position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trader_stocks', 'position')
    op.drop_constraint(None, 'price', type_='foreignkey')
    # ### end Alembic commands ###
