"""empty message

Revision ID: 81e9e8c31bd6
Revises: 47f466c67790
Create Date: 2020-06-15 14:06:43.227227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e9e8c31bd6'
down_revision = '47f466c67790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('market_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock', 'market', ['market_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.drop_column('stock', 'market_id')
    # ### end Alembic commands ###
